{
 "title": "Global View",
 "time": { "from": "2019-05-19T23:00:00.000Z", "to": "2019-06-18T23:00:00.000Z" },
 "panels": [
  { "title": "High level Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sum of Revenue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(taxful_price*basket_count) from baskets join products on baskets.product_id=products.product_id",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Max Customer Spending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select max(temp.sm) from\n  (select customer_id,sum(taxful_price*basket_count) as sm from baskets join products on baskets.product_id=products.product_id  Group BY baskets.customer_id) temp",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Median Spending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select median(temp.sm) from\n  (select customer_id,sum(taxful_price*basket_count) as sm from baskets join products on baskets.product_id=products.product_id  Group BY baskets.customer_id) temp",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Min Customer Spending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select min(temp.sm) from\n  (select customer_id,sum(taxful_price*basket_count) as sm from baskets join products on baskets.product_id=products.product_id  Group BY baskets.customer_id) temp",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Number of sold items per Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select basket_date as date ,sum(basket_count)as sm from baskets group by basket_date",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Average number of sold items / Day",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select avg(temp.transactions) from \n(select basket_date as date ,count(*) as transactions  from baskets Group by basket_date) temp",
     "selectedFormat": 4
    }
   ]
  },
  { "title": "More Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Sales evolution per week",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select temp.week, sum(temp.payed) from\n(select b.basket_date,toMonday(b.basket_date) as week,(b.basket_count*p.taxful_price) as payed from baskets as b Join products as p on p.product_id=b.product_id ) temp\ngroup by temp.week",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Top 10 Products",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "select temp.product_name, count(temp.id) as count from \n(select product_name,b.basket_date,b.product_id as id,p.category from baskets as b left join products as p on p.product_id=b.product_id) temp\nGroup by temp.product_name\nORDER By count DESC\nLIMIT 10",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Diffrence in sales between weeks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "select temp.week, sum(temp.payed) as payed, (payed-neighbor(payed, 1)) as diff  from\n(select b.basket_date,toMonday(b.basket_date) as week,(b.basket_count*p.taxful_price) as payed from baskets as b Join products as p on p.product_id=b.product_id ) temp\ngroup by temp.week\nORDER by temp.week DESC",
     "selectedFormat": 4
    }
   ]
  }
 ]
}